import { NextRequest, NextResponse } from "next/server";
import { serverDb } from "@/lib/rdb-server";

// 学术工具数据
const academicTools = [
  // 文献检索 MCP
  {
    title: "Paper Search MCP",
    title_zh: "Paper Search MCP",
    description: "One-stop access to arXiv, PubMed, bioRxiv, Crossref with built-in deduplication.",
    description_zh: "一站打通 arXiv、PubMed、bioRxiv、Crossref，自带去重功能。",
    category: "literature-search",
    subcategory: "paper-search",
    tags: ["mcp", "arxiv", "pubmed", "crossref", "deduplication"],
    source_repo: "openags/paper-search-mcp",
    source_url: "https://github.com/openags/paper-search-mcp",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "Zotero MCP",
    title_zh: "Zotero MCP",
    description: "1.6k stars, mainstream Zotero MCP for literature management.",
    description_zh: "1.6k stars，主流 Zotero MCP，用于文献管理。",
    category: "literature-search",
    subcategory: "zotero",
    tags: ["mcp", "zotero", "reference-management"],
    source_repo: "54yyyu/zotero-mcp",
    source_url: "https://github.com/54yyyu/zotero-mcp",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "Zotero MCP (Chinese)",
    title_zh: "Zotero MCP 中文版",
    description: "Zotero plugin form with complete Chinese documentation, preferred by Chinese users. 490 stars.",
    description_zh: "Zotero 插件形态，中文文档完善，中文用户首选，490 stars。",
    category: "literature-search",
    subcategory: "zotero",
    tags: ["mcp", "zotero", "chinese", "plugin"],
    source_repo: "cookjohn/zotero-mcp",
    source_url: "https://github.com/cookjohn/zotero-mcp",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "arXiv MCP Server",
    title_zh: "arXiv MCP 服务器",
    description: "Classic arXiv implementation with citation network support.",
    description_zh: "arXiv 经典实现，可拉引用网络。",
    category: "literature-search",
    subcategory: "arxiv",
    tags: ["mcp", "arxiv", "citation-network"],
    source_repo: "blazickjp/arxiv-mcp-server",
    source_url: "https://github.com/blazickjp/arxiv-mcp-server",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "OpenAlex Research MCP",
    title_zh: "OpenAlex 研究 MCP",
    description: "OpenAlex 240M+ papers with citation networks and collaborator graphs.",
    description_zh: "OpenAlex 2.4亿+ 论文，含引用网络与合作者图谱。",
    category: "literature-search",
    subcategory: "openalex",
    tags: ["mcp", "openalex", "citation-network", "collaboration"],
    source_repo: "oksure/openalex-research-mcp",
    source_url: "https://github.com/oksure/openalex-research-mcp",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "Semantic Scholar MCP",
    title_zh: "Semantic Scholar MCP",
    description: "Semantic Scholar 225M+ papers access.",
    description_zh: "Semantic Scholar 2.25亿+ 论文访问。",
    category: "literature-search",
    subcategory: "semantic-scholar",
    tags: ["mcp", "semantic-scholar", "academic-search"],
    source_repo: "xiuyechen/semantic-scholar-mcp",
    source_url: "https://github.com/xiuyechen/semantic-scholar-mcp",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "PubMed MCP Server",
    title_zh: "PubMed MCP 服务器",
    description: "PubMed + Europe PMC + MeSH + Unpaywall, essential for health economics.",
    description_zh: "PubMed + Europe PMC + MeSH + Unpaywall，健康经济学必备。",
    category: "literature-search",
    subcategory: "pubmed",
    tags: ["mcp", "pubmed", "health-economics", "mesh"],
    source_repo: "cyanheads/pubmed-mcp-server",
    source_url: "https://github.com/cyanheads/pubmed-mcp-server",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "Academix",
    title_zh: "Academix",
    description: "Five-in-one: OpenAlex, DBLP, Semantic Scholar, arXiv, CrossRef.",
    description_zh: "OpenAlex、DBLP、SS、arXiv、CrossRef 五合一。",
    category: "literature-search",
    subcategory: "aggregator",
    tags: ["mcp", "aggregator", "multi-source"],
    source_repo: "xingyulu23/Academix",
    source_url: "https://github.com/xingyulu23/Academix",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "ScholarMCP",
    title_zh: "ScholarMCP",
    description: "Search + PDF ingestion + citation management in one.",
    description_zh: "检索 + PDF 摄入 + 引用管理一体。",
    category: "literature-search",
    subcategory: "scholar",
    tags: ["mcp", "pdf", "citation-management"],
    source_repo: "lstudlo/ScholarMCP",
    source_url: "https://github.com/lstudlo/ScholarMCP",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "MCP Zotero (Node)",
    title_zh: "MCP Zotero (Node 版)",
    description: "Node version supporting DOI addition and Unpaywall OA full-text auto-discovery.",
    description_zh: "Node 版，支持 DOI 添加加 Unpaywall OA 自动找全文。",
    category: "literature-search",
    subcategory: "zotero",
    tags: ["mcp", "zotero", "node", "unpaywall", "doi"],
    source_repo: "Xevos117/mcp-zotero",
    source_url: "https://github.com/Xevos117/mcp-zotero",
    status: "PUBLISHED",
    author_id: "system",
  },
  // 引用核验 MCP
  {
    title: "MCP RefChecker",
    title_zh: "MCP 引用核验器",
    description: "Third-party verification (Semantic Scholar, OpenAlex, CrossRef) to prevent AI hallucination citations.",
    description_zh: "第三方核验（Semantic Scholar、OpenAlex、CrossRef），专治 AI 幻觉引用。",
    category: "citation-check",
    subcategory: "verification",
    tags: ["mcp", "citation", "verification", "ai-hallucination"],
    source_repo: "JonasBaath/mcp-refchecker",
    source_url: "https://github.com/JonasBaath/mcp-refchecker",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "GitHub Citation",
    title_zh: "GitHub 引用格式转换",
    description: "One-click conversion between BibTeX, APA, MLA, Chicago, IEEE, Harvard formats.",
    description_zh: "BibTeX、APA、MLA、Chicago、IEEE、Harvard 一键互转。",
    category: "citation-check",
    subcategory: "format-conversion",
    tags: ["citation", "format", "bibtex", "apa", "mla"],
    source_repo: "ezefranca/github-citation",
    source_url: "https://github.com/ezefranca/github-citation",
    status: "PUBLISHED",
    author_id: "system",
  },
  // Deep Research
  {
    title: "Stanford STORM",
    title_zh: "Stanford STORM",
    description: "NAACL'24 paper, multi-perspective Q&A, especially suitable for controversial topics. 25k+ stars.",
    description_zh: "NAACL'24 论文，多视角问答，尤其适合争议话题。25k+ stars。",
    category: "deep-research",
    subcategory: "storm",
    tags: ["agent", "research", "multi-perspective", "controversy"],
    source_repo: "stanford-oval/storm",
    source_url: "https://github.com/stanford-oval/storm",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "LangChain Open Deep Research",
    title_zh: "LangChain 开放深度研究",
    description: "Native MCP compatible deep research framework. 2.7k+ stars.",
    description_zh: "原生 MCP 兼容的深度研究框架。2.7k+ stars。",
    category: "deep-research",
    subcategory: "langchain",
    tags: ["agent", "langchain", "mcp", "deep-research"],
    source_repo: "langchain-ai/open-deep-research",
    source_url: "https://github.com/langchain-ai/open-deep-research",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "HuggingFace smolagents",
    title_zh: "HuggingFace smolagents",
    description: "Reproduce OpenAI Deep Research with code-acting agent. 26k+ stars.",
    description_zh: "复现 OpenAI Deep Research，code-acting agent。26k+ stars。",
    category: "deep-research",
    subcategory: "smolagents",
    tags: ["agent", "huggingface", "code-acting", "deep-research"],
    source_repo: "huggingface/smolagents",
    source_url: "https://github.com/huggingface/smolagents",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "GPT-Researcher",
    title_zh: "GPT 研究员",
    description: "Planner + executor architecture, outputs 5-6 page PDF reports. 16k+ stars.",
    description_zh: "planner + executor，输出 5 到 6 页 PDF。16k+ stars。",
    category: "deep-research",
    subcategory: "gpt-researcher",
    tags: ["agent", "pdf", "planner", "executor"],
    source_repo: "assafelovic/gpt-researcher",
    source_url: "https://github.com/assafelovic/gpt-researcher",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "Local Deep Researcher",
    title_zh: "本地深度研究",
    description: "Fully localized, suitable for sensitive data. 10k+ stars.",
    description_zh: "完全本地化，适合涉及敏感数据。10k+ stars。",
    category: "deep-research",
    subcategory: "local",
    tags: ["agent", "local", "privacy", "sensitive-data"],
    source_repo: "langchain-ai/local-deep-researcher",
    source_url: "https://github.com/langchain-ai/local-deep-researcher",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "PaperQA2 (FutureHouse)",
    title_zh: "PaperQA2 (FutureHouse)",
    description: "Citation-grounded RAG, quality exceeds PhD level. 7k+ stars.",
    description_zh: "citation-grounded RAG，水准超过 PhD。7k+ stars。",
    category: "deep-research",
    subcategory: "paperqa",
    tags: ["agent", "rag", "citation", "phd-level"],
    source_repo: "Future-House/paper-qa",
    source_url: "https://github.com/Future-House/paper-qa",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "Ai2 ScholarQA",
    title_zh: "Ai2 ScholarQA",
    description: "RAG + Claude Sonnet backend, ScholarQABench SOTA by Allen AI.",
    description_zh: "RAG + Claude Sonnet 后端，ScholarQABench SOTA。",
    category: "deep-research",
    subcategory: "scholarqa",
    tags: ["agent", "rag", "claude", "allen-ai", "sota"],
    source_repo: "allenai/ScholarQA",
    source_url: "https://github.com/allenai/ScholarQA",
    status: "PUBLISHED",
    author_id: "system",
  },
  // 系统综述
  {
    title: "SLR-PRISMA",
    title_zh: "SLR-PRISMA",
    description: "Strictly follows PRISMA 2020 guidelines for systematic reviews.",
    description_zh: "严格遵循 PRISMA 2020 的系统综述工具。",
    category: "systematic-review",
    subcategory: "prisma",
    tags: ["prisma", "systematic-review", "guidelines"],
    source_repo: "keemanxp/slr-prisma",
    source_url: "https://github.com/keemanxp/slr-prisma",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "PRISMA Review Tool",
    title_zh: "PRISMA 综述工具",
    description: "MCP-driven PRISMA with AI screening.",
    description_zh: "MCP 驱动的 PRISMA 加 AI 筛选。",
    category: "systematic-review",
    subcategory: "prisma",
    tags: ["mcp", "prisma", "ai-screening"],
    source_repo: "Black-Lights/prisma-review-tool",
    source_url: "https://github.com/Black-Lights/prisma-review-tool",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "ASReview",
    title_zh: "ASReview",
    description: "Active learning for title/abstract screening, Nature Mach Intell paper.",
    description_zh: "主动学习筛 title/abstract，Nature Mach Intell 论文。",
    category: "systematic-review",
    subcategory: "screening",
    tags: ["active-learning", "screening", "nature"],
    source_repo: "asreview/asreview",
    source_url: "https://github.com/asreview/asreview",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "RobotReviewer",
    title_zh: "RobotReviewer",
    description: "Automatic risk of bias assessment, Cochrane collaboration.",
    description_zh: "自动 RoB 评估，Cochrane 合作。",
    category: "systematic-review",
    subcategory: "risk-bias",
    tags: ["rob", "cochrane", "bias-assessment"],
    source_repo: "RobotReviewer/robotreviewer",
    source_url: "https://github.com/RobotReviewer/robotreviewer",
    status: "PUBLISHED",
    author_id: "system",
  },
  // LaTeX
  {
    title: "Overleaf MCP",
    title_zh: "Overleaf MCP",
    description: "Read/write Overleaf via Git, well-known MCP.",
    description_zh: "通过 Git 读写 Overleaf，很知名的 MCP。",
    category: "latex",
    subcategory: "overleaf",
    tags: ["mcp", "overleaf", "git", "collaboration"],
    source_repo: "mjyoo2/OverleafMCP",
    source_url: "https://github.com/mjyoo2/OverleafMCP",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "Overleaf MCP (Free)",
    title_zh: "Overleaf MCP (免费版)",
    description: "24 tools, free Overleaf version can also push.",
    description_zh: "24 个工具，免费版 Overleaf 也能 push。",
    category: "latex",
    subcategory: "overleaf",
    tags: ["mcp", "overleaf", "free", "24-tools"],
    source_repo: "ghostiee-11/overleaf-mcp",
    source_url: "https://github.com/ghostiee-11/overleaf-mcp",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "Overleaf MCP Server",
    title_zh: "Overleaf MCP 服务器",
    description: "Parse sections, formulas, citations.",
    description_zh: "解析 section、公式、citation。",
    category: "latex",
    subcategory: "overleaf",
    tags: ["mcp", "overleaf", "parser", "formula"],
    source_repo: "YounesBensafia/overleaf-mcp-server",
    source_url: "https://github.com/YounesBensafia/overleaf-mcp-server",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "arXiv LaTeX MCP",
    title_zh: "arXiv LaTeX MCP",
    description: "Fetch arXiv LaTeX source code for precise formula parsing.",
    description_zh: "抓 arXiv LaTeX 源码，公式精确解析。",
    category: "latex",
    subcategory: "arxiv",
    tags: ["mcp", "arxiv", "latex", "formula"],
    source_repo: "takashiishida/arxiv-latex-mcp",
    source_url: "https://github.com/takashiishida/arxiv-latex-mcp",
    status: "PUBLISHED",
    author_id: "system",
  },
  // 网页抓取
  {
    title: "Firecrawl MCP Server",
    title_zh: "Firecrawl MCP 服务器",
    description: "Industry benchmark, 6.5k+ stars. Supports markdown, JSON, JS rendering.",
    description_zh: "行业标杆，6.5k+ stars。支持 markdown、JSON、JS 渲染。",
    category: "web-scraping",
    subcategory: "firecrawl",
    tags: ["mcp", "web-scraping", "markdown", "json", "js-rendering"],
    source_repo: "firecrawl/firecrawl-mcp-server",
    source_url: "https://github.com/firecrawl/firecrawl-mcp-server",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "CRW (Rust)",
    title_zh: "CRW (Rust 版)",
    description: "Rust implementation, Firecrawl compatible API, self-hosted.",
    description_zh: "Rust 实现，Firecrawl 兼容 API，自托管。",
    category: "web-scraping",
    subcategory: "crw",
    tags: ["mcp", "rust", "firecrawl-compatible", "self-hosted"],
    source_repo: "us/crw",
    source_url: "https://github.com/us/crw",
    status: "PUBLISHED",
    author_id: "system",
  },
  {
    title: "Microsoft Playwright MCP",
    title_zh: "Microsoft Playwright MCP",
    description: "Suitable for data collection requiring login.",
    description_zh: "适合需登录的数据采集。",
    category: "web-scraping",
    subcategory: "playwright",
    tags: ["mcp", "playwright", "login", "automation"],
    source_repo: "microsoft/playwright-mcp",
    source_url: "https://github.com/microsoft/playwright-mcp",
    status: "PUBLISHED",
    author_id: "system",
  },
];

export async function POST(_request: NextRequest) {
  try {
    const results = [];
    
    for (const tool of academicTools) {
      const result = await serverDb.from("skill").insert(tool).execute();
      if (result.error) {
        results.push({ title: tool.title, error: result.error.message });
      } else {
        results.push({ title: tool.title, success: true });
      }
    }

    return NextResponse.json({ results });
  } catch (error) {
    console.error("Failed to insert academic tools:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
